### PR TITLE
Add Xenon resource outbound message

### PR DESCRIPTION
**Pull request by PBechon**
Fix for #1 

Since the ID of packet was changed, this pull request may need to be adapted with the new name, but the code to send the packet should be OK. I did not figure out how to untangle this mess of having my version not based on the develop branch ...

### CODE REVIEW

**Comment by LRTNZ** [comment]
@PBechon I will look at this later today - I was actually about to program in this feature myself.

What do you mean you cannot work out how to untangle the mess of not having your version based off of the dev branch?

**Comment by LRTNZ** [comment]
Actually, looking at this - it may be easier if I go in and do this one from scratch, as I want to tweak the layout of all of this code, to match the plans I have regarding a bit of a restructure down the line.

**Comment by PBechon** [comment]
I had tried to pull your new version of the IDs to merge by myself the two branch (develop and mine). But I did not succeed, thus this pull request cannot be merged as is.

By the way you changed the message ID but they are hardcoded in some places (see Resources.cs for instance, line 43 to 76). I assume you planned to update those as well ?

**Comment by LRTNZ** [comment]
> 
> 
> I had tried to pull your new version of the IDs to merge by myself the two branch (develop and mine). But I did not succeed, thus this pull request cannot be merged as is.
> 

Yeah, I noticed that it has some merge conflicts in the file - it is not the worst one to resolve in this case, however in future you will need to merge/rebase upstream changes to prevent conflicts when you go to create a merge request.

> By the way you changed the message ID but they are hardcoded in some places (see Resources.cs for instance, line 43 to 76). I assume you planned to update those as well ?

Ok, if that is the case, I do need to do a bit more digging in the code, and work out how best I want to tackle that. So thanks for the work, but I will tackle this one myself - mainly due to all of the ID stuff I am contemplating reworking!

**Comment by LRTNZ** [comment]
Also join the discord server! The link is in the readme on the develop branch.

**Comment by TheDicko** [comment]
Any way i can test this?

**Comment by LRTNZ** [comment]
No, not really - the code will not merge cleanly with the current code base, and all the resource values are being changed around. I hope to get this sorted a bit later today - it's after 5am, I am not going to sort this for the next few hours till I have had some sleep! 🙂

**Comment by TheDicko** [comment]
> No, not really - the code will not merge cleanly with the current code base, and all the resource values are being changed around. I hope to get this sorted a bit later today - it's after 5am, I am not going to sort this for the next few hours till I have had some sleep! 🙂

No problem , get some sleep my friend !

**Pull request closed without merging**
