### PR TITLE
Add a Dispatcher to do the function calls that can trigger GUI or sound.

### PR DESCRIPTION
**Pull request by PBechon**
This dispatcher is used for the CAG messages.
This prevent a crash when a ScreenMessage is displayed during the CAG activation (for instance when the activation is not allowed due to an electrical charge to 0).

This PR use a library that is included in the Contrib folder with its own license.

If this works correctly, other Provider could use this dispatcher. Currently the Action dispatcher for instance uses another trick to call its activation from the main thread, but this limit it to one activation per tick (see the TODO on line 18 of Action.cs)

### CODE REVIEW

**Comment by LRTNZ** [comment]
Do you have a link to the source of this lib? A Github link that could be included somewhere would be great!

But otherwise, it looks like it could be a good solution.

**Comment by PBechon** [comment]
The link was added in the README of the folder containing the library source code.

**Comment by PBechon** [comment]
I added a commit to fix the timewarp crash to desktop that was due to a message that should be displayed. This allow to timewarp to a given time (apoapsis, periapsis, etc.) even if the current rate is not x1.

**Comment by LRTNZ** [comment]
> 
> 
> I added a commit to fix the timewarp crash to desktop that was due to a message that should be displayed. This allow to timewarp to a given time (apoapsis, periapsis, etc.) even if the current rate is not x1.

Sounds good - however I wonder if we would still want the timewarp to next time to be blocked, while another timewarp to next time is still running?

**Comment by PBechon** [comment]
The game prevents a TW to a given time if you are already in a TW to a given time. The crash was caused but the message telling you that by the way. 
What this modification does is allow a TW to a specific time if you are already in a TW with a set rate.

**Pull request merged**
