### PR TITLE
Addition of 3 new messages for DeltaV and BurnTime

### PR DESCRIPTION
**Pull request by PBechon**
First proposal for adding DeltaV and BurnTime message (see #2)

DeltaV and BurnTime tested on my controller. In some cases the current stage is not set (for instance before launch), so there is a need to test it. For now, I return 0 in those case.

### CODE REVIEW

**Comment by LRTNZ** [comment]
Looks good so far! I am trying to see if I can find a tweak we can make in order to have the first stage dV be provided when the ship is not in flight. As currently from what I can see, your code is looking for the current active ship, that is in flight?

**Comment by PBechon** [comment]
Yes, the code is looking for the active stage of the active vessel. There is several things that could be improved. For instance before launch, there is no stage active. We could in this case look for the first stage that contains deltaV and display this one.

But in flight, if you have several stage without payload the current deltaV will be 0 until the engine are started. In this case it could make sense to display the first stage that contains deltaV (as before launch). But we need to discriminate in this case an empty current stage (where we want to display 0) and a current stage without engine where we want to display the next stage with deltaV.

**Comment by LRTNZ** [comment]
No, I think the deltaV of the current stage, even if it has no deltaV is best. 

As you said - What happens when you run out of deltaV in your current stage, and the mod switches to the next stage with deltaV - I don't think most people would find that particularly useful, as some people may have empty tanks they could be dropping off somewhere for a refueling space station. Which would screw up the logic of an empty stage, and one that has never had dV.

That is also before we reach the fun of fuel lines existing.

**Comment by PBechon** [comment]
What I had in mind was the following logic (but I did not investigate if the API gives enough information):

If there is an active stage with any deltaV capacity, we display it (so 0 for empty tank, non 0 in other cases)
If not (either before launch or during flight), look for the next stage that has any deltaV capacity and display it.

This way you have 0 displayed when your tank is empty, but not 0 when your next stage is only fairing. But I haven't looked yet into the feasibility. What do you think about this logic ?

**Comment by LRTNZ** [comment]
I see two sides to it. First, I do like the idea of looking ahead to provide the next usable dV stage.

However if you are on a fairing stage, technically your current dV is zero. By not displaying the next useful stage, we avoid the ambiguity of users having to potentially work out what the dV is being shown for, and wondering why their throttle may not be working etc.

Also, what happens if a user has an inline lander that they rearrange the the staging structure/detach mid flight for an Apollo style mission?

**Comment by PBechon** [comment]
I modified my PR to account the fact that before launch, the deltaV displayed should not be 0. I instead used the first stage with deltaV (to avoid displaying 0 if the first stage is only stabilizers).

During my test, I encountered strange behavior where the deltaV values were quickly switching between 2 values (with the stock Ariane V). But I did also happen in the deltaV display of stock KSP, so I assume the problem is on KSP computation and not on this mod.

**Comment by LRTNZ** [comment]
I am going to accept this PR tentatively, as I like the way that it is headed, and that it provides a good framework. However I think we will have to do some testing on the code, as I have a feeling there may be an odd edge case or two that we have not considered that may cause an issue.

**Comment by PBechon** [comment]
Agree, with more usage we will probably see things to improve

**Pull request merged**
